version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:e2e
workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          - requires:
              - build-and-test
          - filters:
            branches:
              only: main
