version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-npm: false
      - node/install-yarn:
          version: 1.22.19
      - run:
          command: yarn
      - run:
          command: yarn test:e2e
workflows:
  build-and-test:
    jobs:
      - build-and-test
